SELECT * FROM TV.USER.PROFILE;

---EDA-Explanaory Data Analysis

---Minimum age
SELECT MIN(AGE) AS MINIMUM_AGE
FROM TV.USER.PROFILE;

---Maximum age
SELECT MAX(AGE) AS MAXIMUM_AGE  
FROM TV.USER.PROFILE;

-- Distinct Race types
SELECT DISTINCT RACE 
FROM TV.USER.PROFILE;

-- Age Distribution
SELECT
AGE,
CASE WHEN AGE BETWEEN 0 AND 18 THEN 'YOUNG'
     WHEN AGE BETWEEN 19 AND 35 THEN 'ADULT' 
     WHEN AGE BETWEEN 36 AND 75 THEN 'YOUNG ADULT'
ELSE 'SENIOR'
END AS AGE_BRACKET
FROM TV.USER.PROFILE;

-- Province distribution
SELECT
PROVINCE,
CASE WHEN PROVINCE = 'GAUTENG' THEN 'GAUTENG'
     WHEN PROVINCE = 'Limpopo' THEN 'LIMPOPO'
     WHEN PROVINCE = 'Mpumalanga' THEN 'MPUMALANGA'
     WHEN PROVINCE = 'Western Cape' THEN 'WESTERN CAPE'
     WHEN PROVINCE = 'Eastern Cape' THEN 'EASTERN CAPE'
     WHEN PROVINCE = 'Northern Cape' THEN 'NORTHERN CAPE'
     WHEN PROVINCE = 'Free State' THEN 'FREE STATE'
     WHEN PROVINCE = 'North West' THEN 'NORTH WEST'
     WHEN PROVINCE = 'Kwazulu Natal' THEN 'Kwazulu Natal'
ELSE 'NONE'
END AS PROVINCE_BRACKET
FROM TV.USER.PROFILE;

-- Create view with categorized data
CREATE OR REPLACE VIEW TV.USER.USER_PROFILE_VIEW AS
SELECT
    USERID,  
    AGE,
    CASE 
        WHEN AGE BETWEEN 0 AND 18 THEN 'YOUNG'
        WHEN AGE BETWEEN 19 AND 35 THEN 'ADULT'
        WHEN AGE BETWEEN 36 AND 75 THEN 'YOUNG ADULT'
        ELSE 'SENIOR'
    END AS AGE_BRACKET,
    
    CASE
        WHEN GENDER = 'female' THEN 'FEMALE'
        WHEN GENDER = 'male' THEN 'MALE'
        ELSE 'PREFER NOT TO SAY'
    END AS GENDER_BRACKET,
    
    CASE 
        WHEN PROVINCE = 'Gauteng' THEN 'GAUTENG'
        WHEN PROVINCE = 'Limpopo' THEN 'LIMPOPO'
        WHEN PROVINCE = 'Mpumalanga' THEN 'MPUMALANGA'
        WHEN PROVINCE = 'Western Cape' THEN 'WESTERN CAPE'
        WHEN PROVINCE = 'Eastern Cape' THEN 'EASTERN CAPE'
        WHEN PROVINCE = 'Northern Cape' THEN 'NORTHERN CAPE'
        WHEN PROVINCE = 'Free State' THEN 'FREE STATE'
        WHEN PROVINCE = 'North West' THEN 'NORTH WEST'
        WHEN PROVINCE = 'Kwazulu Natal' THEN 'KWAZULU NATAL'
        ELSE 'NONE'
    END AS PROVINCE_BRACKET,
    
    CASE
        WHEN RACE ='black' THEN 'BLACK'
        WHEN RACE ='white' THEN 'WHITE'
        WHEN RACE ='coloured' THEN 'COLOURED'
        WHEN RACE ='indian_asian' THEN 'INDIAN ASIAN'
        WHEN RACE ='other' THEN 'OTHER'
        ELSE 'NOT DISCLOSED'
    END AS RACE_BRACKET
FROM TV.USER.PROFILE;

---Test the view
SELECT AGE_BRACKET, PROVINCE_BRACKET, GENDER_BRACKET, RACE_BRACKET
FROM TV.USER.USER_PROFILE_VIEW;


-- Which age dominates each gender
SELECT 
    GENDER_BRACKET,
    AGE_BRACKET,
    COUNT(*) AS User_Count
FROM TV.USER.USER_PROFILE_VIEW
GROUP BY GENDER_BRACKET, AGE_BRACKET
ORDER BY GENDER_BRACKET, User_Count DESC;

-- Which race dominates each province
SELECT 
    PROVINCE_BRACKET,
    RACE_BRACKET,
    COUNT(*) AS Count_Users
FROM TV.USER.USER_PROFILE_VIEW
GROUP BY PROVINCE_BRACKET, RACE_BRACKET
ORDER BY PROVINCE_BRACKET, Count_Users DESC;

-- Age distribution by race
SELECT
    RACE_BRACKET,
    AGE_BRACKET,
    COUNT(*) AS Count_Users
FROM TV.USER.USER_PROFILE_VIEW
GROUP BY RACE_BRACKET, AGE_BRACKET
ORDER BY RACE_BRACKET, AGE_BRACKET;

select * from TV.USERS.PROFILE_VIEW;
SELECT * FROM TV.USER.PROFILE;



